### ISSUE TITLE
Ether.fi weETH Balancer Integration

### ISSUE THREAD

**Issue by solipsis** [threerocks-defi/code-review#28] opened 2023-10-11 20:35 UTC
### Type of Smart Contract

Rate Provider

### Contract Source Code

https://github.com/etherfi-protocol/shallow-smart-contracts/blob/master/src/WeETH.sol

### Additional Links

https://goerli.etherscan.io/address/0xAc687b5ccd042e0d70405219112d95035938e3e8#readProxyContract

### Protocol Documentation

https://etherfi.gitbook.io/etherfi/ether.fi-whitepaper

### Protocol Audits

https://etherfi.gitbook.io/etherfi/security/audits

### Terms and Conditions

- [X] The protocol to be integrated has been audited by at least one security firm or independent researcher.
- [X] If deployed, the contract is verified on etherscan.
- [X] The contract does not rely upon an EOA to supply any critical data (e.g., price).
- [X] If upgradeable, the contract's administrator is not an EOA.

**Comment by rabmarut** [comment] 2023-10-12 17:07
Thank you for your request. We will complete this review next week before Thursday (October 19).

**Comment by rabmarut** [comment] 2023-10-18 19:31
Hi @solipsis, I think this code should work, but of course our review does not constitute a full audit of the codebase; I am only looking at the Balancer integration specifically.

I can't provide a full review until the contracts are deployed to a production network. Our review process includes the live configuration of the system (such as identifying all of the accounts possessing admin roles). We want to ensure that all admin privileges are sufficiently limited (i.e., EOAs are not configuring the system without bound). Multisigs, timelocks, etc. are better.

I also noticed one strange thing as I was reviewing the pricing logic. When the `LiquidityPool` receives ETH via transfer, this **does not** impact the price because the sum `totalValueInLp + totalValueOutOfLp` remains unchanged. This is good in the sense that it protects against donation attacks.

```solidity
receive() external payable {
    if (msg.value > type(uint128).max) revert InvalidAmount();
    totalValueOutOfLp -= uint128(msg.value);
    totalValueInLp += uint128(msg.value);
}
```

But I wonder, what happens if ETH is donated to this contract? It leaves an imaginary hole in `totalValueOutOfLp`. Would  the admin plan to gradually re-introduce this balance using `rebase()`?

**Comment by seongyun-ko** [comment] 2023-10-18 23:40
> Hi @solipsis, I think this code should work, but of course our review does not constitute a full audit of the codebase; I am only looking at the Balancer integration specifically.
> 
> I can't provide a full review until the contracts are deployed to a production network. Our review process includes the live configuration of the system (such as identifying all of the accounts possessing admin roles). We want to ensure that all admin privileges are sufficiently limited (i.e., EOAs are not configuring the system without bound). Multisigs, timelocks, etc. are better.
> 
> I also noticed one strange thing as I was reviewing the pricing logic. When the `LiquidityPool` receives ETH via transfer, this **does not** impact the price because the sum `totalValueInLp + totalValueOutOfLp` remains unchanged. This is good in the sense that it protects against donation attacks.
> 
> ```solidity
> receive() external payable {
>     if (msg.value > type(uint128).max) revert InvalidAmount();
>     totalValueOutOfLp -= uint128(msg.value);
>     totalValueInLp += uint128(msg.value);
> }
> ```
> 
> But I wonder, what happens if ETH is donated to this contract? It leaves an imaginary hole in `totalValueOutOfLp`. Would the admin plan to gradually re-introduce this balance using `rebase()`?

Hi, yeah your guess is exactly correct.
Periodically, we perform `rebase()` which will  re-introduce that balance

**Comment by rabmarut** [comment] 2023-10-18 23:53
Great, thank you! Please let me know when the contracts are deployed to production so that I can produce the full review for the Balancer ecosystem.

**Comment by Zen-Maxi** [comment] 2023-11-19 15:23
@rabmarut i believe the gauge proposal will go up this week. The token itself returns it's rate via getRate. https://etherscan.io/address/0xCd5fE23C85820F7B72D0926FC9b05b43E359b7ee#readProxyContract Please let us know when you think this can be done. Ideally before Thursday November 23rd.

**Comment by seongyun-ko** [comment] 2023-11-19 19:14
@rabmarut the contracts are deployed to production! Can you produce the full review of it?

**Comment by rabmarut** [comment] 2023-11-19 22:41
Thanks @Zen-Maxi and @seongyun-ko, I'll take a look at the deployment tomorrow and let you know if there are any glaring issues. The full review (assuming no issues) will be merged by Wednesday to allow for voting on Thursday.

**Comment by rabmarut** [comment] 2023-11-22 16:35
Hi @seongyun-ko and @Zen-Maxi, please see #38 where I've ruled the current system **UNSAFE**. I'm sorry it took a while to reach this ruling; the issue is at the very end of the administration chain.

There is an EOA (https://etherscan.io/address/0xf8a86ea1Ac39EC529814c377Bd484387D395421e) with upgrade power over core system components (`EtherFiAdmin` and `EtherFiOracle`). It could upgrade the system to a version that allows it to arbitrarily increase the price without bound. This level of trust is unacceptable as it would be catastrophic to Balancer pools containing `weETH`.

Please let me know if you believe my understanding is incorrect.

**Comment by solipsis** [comment] 2023-11-22 22:00
> Hi @seongyun-ko and @Zen-Maxi, please see #38 where I've ruled the current system **UNSAFE**. I'm sorry it took a while to reach this ruling; the issue is at the very end of the administration chain.
> 
> There is an EOA (https://etherscan.io/address/0xf8a86ea1Ac39EC529814c377Bd484387D395421e) with upgrade power over core system components (`EtherFiAdmin` and `EtherFiOracle`). It could upgrade the system to a version that allows it to arbitrarily increase the price without bound. This level of trust is unacceptable as it would be catastrophic to Balancer pools containing `weETH`.
> 
> Please let me know if you believe my understanding is incorrect.

Thank you for pointing this out. This has been corrected. Both contracts are now owned by our geographically distributed, hardware wallet backed multi-sig.

**Comment by rabmarut** [comment] 2023-11-23 03:42
@solipsis Thanks for correcting this. I'll take a look tomorrow morning and publish the updated review.

Cc: @Zen-Maxi

**Comment by rabmarut** [comment] 2023-11-23 14:55
@solipsis and @Zen-Maxi, I've confirmed the changes and will prepare the changes to the final review now.

**Closed** 2023-11-23 18:24 UTC
Labels: confirmed, rate provider, request
